export const pageId = {
	"home": 1,
	"about": 2,
	"service": 3,
	"myadmedika-home": 4,
	"mymerchant-home": 5,
	"provider": 6,
	"provider-client": 30,
	"provider-network": 31,
	"provider-join": 32,
	"news": 7,
	"news-category": 33,
	"news-download-corner": 34,
	"news-faq": 37,
	"career": 8,
	"contact": 9,
	"terms": 11,
	"search": 12,
	"myadmedika-faq": 10
}